# src/db_oracle.py
import os, json, datetime as dt
import oracledb
from dotenv import load_dotenv; load_dotenv()

# ENV
ORA_HOST = os.getenv("ORA_HOST", "localhost")
ORA_PORT = int(os.getenv("ORA_PORT", "1521"))
ORA_SID  = os.getenv("ORA_SID", "orcl")
ORA_USER = os.getenv("ORA_USER")
ORA_PASS = os.getenv("ORA_PASSWORD")
SCHEMA   = os.getenv("ORA_SCHEMA", ORA_USER or "").upper()  # ex.: RM558897

def _dsn():
    return oracledb.makedsn(ORA_HOST, ORA_PORT, sid=ORA_SID)

def _connect():
    # Configurar timeout e retry
    try:
        return oracledb.connect(
            user=ORA_USER, 
            password=ORA_PASS, 
            dsn=_dsn()
        )
    except Exception as e:
        print(f"[ERRO] Falha na conexão Oracle: {e}")
        raise

def _ts(epoch_s: float) -> dt.datetime:
    # timestamp UTC com tzinfo (Oracle TIMESTAMP WITH TIME ZONE)
    return dt.datetime.fromtimestamp(epoch_s, tz=dt.timezone.utc)

def init_db():
    """Cria tabelas/views se não existirem (idempotente). Rode uma vez; ignora erros de 'já existe'."""
    ddl = [
        # EVENTS
        f"""
        BEGIN
          EXECUTE IMMEDIATE q'[
            CREATE TABLE {SCHEMA}.events (
              id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              ts          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
              person_id   VARCHAR2(64)   NOT NULL,
              camera_id   VARCHAR2(32)   NOT NULL,
              event_type  VARCHAR2(30)   NOT NULL,
              roi_id      VARCHAR2(128),
              confidence  NUMBER(5,4),
              extra_json  CLOB CHECK (extra_json IS JSON)
            )
          ]';
        EXCEPTION WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;  -- ORA-00955: name is already used by an existing object
        END;
        """,
        f"""
        BEGIN
          EXECUTE IMMEDIATE 'ALTER TABLE {SCHEMA}.events ADD CONSTRAINT events_type_chk
            CHECK (event_type IN (''enter_store'',''dwell_low'',''reach_medium'',''place_in_cart_high'',''depart_high''))';
        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2264 THEN RAISE; END IF; END; -- já existe
        """,
        f"""
        BEGIN
          EXECUTE IMMEDIATE 'ALTER TABLE {SCHEMA}.events ADD CONSTRAINT events_conf_range
            CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))';
        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2264 THEN RAISE; END IF; END;
        """,
        f"BEGIN EXECUTE IMMEDIATE 'CREATE INDEX {SCHEMA}.idx_events_ts ON {SCHEMA}.events (ts)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;",
        f"BEGIN EXECUTE IMMEDIATE 'CREATE INDEX {SCHEMA}.idx_events_person ON {SCHEMA}.events (person_id)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;",
        f"BEGIN EXECUTE IMMEDIATE 'CREATE INDEX {SCHEMA}.idx_events_cam_ts ON {SCHEMA}.events (camera_id, ts)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;",

        # PATHS
        f"""
        BEGIN
          EXECUTE IMMEDIATE q'[
            CREATE TABLE {SCHEMA}.paths (
              id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              ts         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
              person_id  VARCHAR2(64) NOT NULL,
              x          NUMBER(10,2) NOT NULL,
              y          NUMBER(10,2) NOT NULL,
              roi_id     VARCHAR2(128),
              camera_id  VARCHAR2(32) NOT NULL
            )
          ]';
        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
        """,
        f"BEGIN EXECUTE IMMEDIATE 'CREATE INDEX {SCHEMA}.idx_paths_cam_ts ON {SCHEMA}.paths (camera_id, ts)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;",

        # SESSIONS
        f"""
        BEGIN
          EXECUTE IMMEDIATE q'[
            CREATE TABLE {SCHEMA}.sessions (
              person_id  VARCHAR2(64) PRIMARY KEY,
              first_ts   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
              last_ts    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
              camera_id  VARCHAR2(32) NOT NULL
            )
          ]';
        EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
        """,

        # VIEWS
        f"""
        BEGIN
          EXECUTE IMMEDIATE q'[
            CREATE OR REPLACE VIEW {SCHEMA}.v_funnel_camera AS
            SELECT
              camera_id,
              SUM(CASE WHEN event_type = 'dwell_low' THEN 1 ELSE 0 END) AS low_intent,
              SUM(CASE WHEN event_type = 'reach_medium' THEN 1 ELSE 0 END) AS med_intent,
              SUM(CASE WHEN event_type IN ('depart_high','place_in_cart_high') THEN 1 ELSE 0 END) AS high_intent,
              MIN(ts) AS first_ts,
              MAX(ts) AS last_ts
            FROM {SCHEMA}.events
            GROUP BY camera_id
          ]';
        END;
        """,
        f"""
        BEGIN
          EXECUTE IMMEDIATE q'[
            CREATE OR REPLACE VIEW {SCHEMA}.v_funnel_roi AS
            SELECT
              camera_id,
              NVL(roi_id,'(none)') AS roi_id,
              SUM(CASE WHEN event_type = 'dwell_low' THEN 1 ELSE 0 END) AS low_intent,
              SUM(CASE WHEN event_type = 'reach_medium' THEN 1 ELSE 0 END) AS med_intent,
              SUM(CASE WHEN event_type IN ('depart_high','place_in_cart_high') THEN 1 ELSE 0 END) AS high_intent
            FROM {SCHEMA}.events
            GROUP BY camera_id, NVL(roi_id,'(none)')
          ]';
        END;
        """,
        f"""
        BEGIN
          EXECUTE IMMEDIATE q'[
            CREATE OR REPLACE VIEW {SCHEMA}.v_events_ts_1min AS
            SELECT
              CAST(TRUNC(ts,'MI') AS TIMESTAMP) AS t_min,
              camera_id,
              NVL(roi_id,'(none)') AS roi_id,
              SUM(CASE WHEN event_type = 'dwell_low' THEN 1 ELSE 0 END) AS low_intent,
              SUM(CASE WHEN event_type = 'reach_medium' THEN 1 ELSE 0 END) AS med_intent,
              SUM(CASE WHEN event_type IN ('depart_high','place_in_cart_high') THEN 1 ELSE 0 END) AS high_intent
            FROM {SCHEMA}.events
            GROUP BY TRUNC(ts,'MI'), camera_id, NVL(roi_id,'(none)')
          ]';
        END;
        """,
        f"""
        BEGIN
          EXECUTE IMMEDIATE q'[
            CREATE OR REPLACE VIEW {SCHEMA}.v_heatmap_bins_20px AS
            SELECT
              camera_id,
              NVL(roi_id,'(none)') AS roi_id,
              FLOOR(x/20) AS xbin,
              FLOOR(y/20) AS ybin,
              COUNT(*) AS n
            FROM {SCHEMA}.paths
            GROUP BY camera_id, NVL(roi_id,'(none)'), FLOOR(x/20), FLOOR(y/20)
          ]';
        END;
        """,
    ]
    with _connect() as conn:
        with conn.cursor() as cur:
            for block in ddl:
                cur.execute(block)
        conn.commit()

def log_event(ts, person_id, camera_id, event_type, roi_id=None, conf=None, extra=None):
    payload = json.dumps(extra) if extra else None
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""INSERT INTO {SCHEMA}.events
                (ts, person_id, camera_id, event_type, roi_id, confidence, extra_json)
                VALUES (:ts, :pid, :cam, :etype, :roi, :conf, :j)""",
            dict(ts=_ts(ts), pid=person_id, cam=camera_id,
                 etype=event_type, roi=roi_id, conf=conf, j=payload)
        )
        conn.commit()

def log_path(ts, person_id, x, y, roi_id=None, camera_id=None):
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""INSERT INTO {SCHEMA}.paths
                (ts, person_id, x, y, roi_id, camera_id)
                VALUES (:ts, :pid, :x, :y, :roi, :cam)""",
            dict(ts=_ts(ts), pid=person_id, x=float(x), y=float(y), roi=roi_id, cam=camera_id)
        )
        conn.commit()

def upsert_session(ts, person_id, camera_id):
    with _connect() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            MERGE INTO {SCHEMA}.sessions s
            USING (SELECT :pid person_id, :ts ts, :cam camera_id FROM dual) v
              ON (s.person_id = v.person_id)
            WHEN MATCHED THEN UPDATE SET s.last_ts = v.ts, s.camera_id = v.camera_id
            WHEN NOT MATCHED THEN INSERT (person_id, first_ts, last_ts, camera_id)
                 VALUES (v.person_id, v.ts, v.ts, v.camera_id)
            """,
            dict(pid=person_id, ts=_ts(ts), cam=camera_id)
        )
        conn.commit()
